name: flutter_sapo_two
description: Project Sapo two
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.6
  equatable: ^2.0.7
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  get_it: 8.0.3
  intl: ^0.19.0
  st_post_data:
    path: packages/features/st_post_data
  st_post_domain:
    path: packages/features/st_post_domain
  st_ui:
    path: packages/core/st_ui
  st_utils:
    path: packages/core/st_utils

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
