name: st_post_data
description: post data package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.6.6
  oxidized: 6.2.0
  st_post_domain:
    path: ../../features/st_post_domain
  st_utils:
    path: ../../core/st_utils

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
