// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3M76pkapDqvd7f-qB-cqzJ_vkll6PIc',
    appId: '1:1046023961211:web:f7692523224efdc2ae00de',
    messagingSenderId: '1046023961211',
    projectId: 'sapo-two',
    authDomain: 'sapo-two.firebaseapp.com',
    storageBucket: 'sapo-two.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeih-rQuNG2riwiz3PJbzfaMXcBr8XxAs',
    appId: '1:1046023961211:android:e148805c031ac75eae00de',
    messagingSenderId: '1046023961211',
    projectId: 'sapo-two',
    storageBucket: 'sapo-two.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0kyjzTHA3fJHDu6-cbfQIfW72vbdDAqU',
    appId: '1:1046023961211:ios:191e35dad7ecb771ae00de',
    messagingSenderId: '1046023961211',
    projectId: 'sapo-two',
    storageBucket: 'sapo-two.firebasestorage.app',
    iosBundleId: 'com.sapo.two.flutter-sapo-two',
  );
}
